/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class ClientAPI_StringVec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientAPI_StringVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_StringVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_StringVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClientAPI_StringVec() {
    this(ovpncliJNI.new_ClientAPI_StringVec__SWIG_0(), true);
  }

  public ClientAPI_StringVec(long n) {
    this(ovpncliJNI.new_ClientAPI_StringVec__SWIG_1(n), true);
  }

  public long size() {
    return ovpncliJNI.ClientAPI_StringVec_size(swigCPtr, this);
  }

  public long capacity() {
    return ovpncliJNI.ClientAPI_StringVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ovpncliJNI.ClientAPI_StringVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ovpncliJNI.ClientAPI_StringVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ovpncliJNI.ClientAPI_StringVec_clear(swigCPtr, this);
  }

  public void add(String x) {
    ovpncliJNI.ClientAPI_StringVec_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return ovpncliJNI.ClientAPI_StringVec_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    ovpncliJNI.ClientAPI_StringVec_set(swigCPtr, this, i, val);
  }

}
